ERROR_INVALID_CPF = "CPF inválido"
ERROR_INVALID_PHONE = "Telefone inválido"
ERROR_INVALID_EMAIL = "Email inválido"
ERROR_INVALID_PHONE_OPTIONAL = "Telefone opcional inválido"
ERROR_INVALID_FORMAT_BIRTH_DATE = "O formato da data deve ser YYYY-MM-DD"
ERROR_INVALID_FORMAT_GENDER = "Gênero invalido, escolha entre M, F ou Z"
ERROR_SERVER_ERROR = "Erro no servidor: "