ERROR_INVALID_CPF = "CPF inválido"
ERROR_INVALID_PHONE = "Telefone inválido"
ERROR_INVALID_EMAIL = "Email inválido"
ERROR_INVALID_PHONE_OPTIONAL = "Telefone opcional inválido"
ERROR_SERVER_ERROR = "Erro no servidor: "